### PR TITLE
Arweave reupload with correct content type

### PR DESCRIPTION
**Pull request by Necmttn**
command (tutorials/polkadot-build-a-poe-decentralized-app) yarn run content:publish --force --skip-images exited (1)
command (tutorials/polygon-create-a-donation-dapp-on-polygon) yarn run content:publish --force --skip-images exited (1) 

```
@builderdao-learn/a-super-cool-tutorial:content:publish: 🔶 Failed to update ceramic metadata
@builderdao-learn/a-super-cool-tutorial:content:publish: Error: HTTP request to 'https://ceramic-clay.3boxlabs.com/api/v0/commits' failed with status 'Internal Server Error': {"error":"invalid_jws: not a valid verificationMethod for issuer: did:key:z6MkvFd9CxR9eNL1rFCMnsvmLYazqtdvVt6rVTegY3KveVxF#z6MkvFd9CxR9eNL1rFCMnsvmLYazqtdvVt6rVTegY3KveVxF"}
@builderdao-learn/a-super-cool-tutorial:content:publish:     at Object.fetchJson (/Users/necmttn/Projects/crypto/kafe/espresso/node_modules/@ceramicnetwork/common/lib/utils/http-utils.js:35:15)
@builderdao-learn/a-super-cool-tutorial:content:publish:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
@builderdao-learn/a-super-cool-tutorial:content:publish:     at async Function.applyCommit (/Users/necmttn/Projects/crypto/kafe/espresso/node_modules/@ceramicnetwork/http-client/lib/document.js:60:27)
@builderdao-learn/a-super-cool-tutorial:content:publish:     at async CeramicClient.applyCommit (/Users/necmttn/Projects/crypto/kafe/espresso/node_modules/@ceramicnetwork/http-client/lib/ceramic-http-client.js:97:26)
@builderdao-learn/a-super-cool-tutorial:content:publish:     at async TileDocument.update (/Users/necmttn/Projects/crypto/kafe/espresso/node_modules/@ceramicnetwork/stream-tile/lib/tile-document.js:140:25)
@builderdao-learn/a-super-cool-tutorial:content:publish:     at async /Users/necmttn/Projects/crypto/kafe/espresso/packages/cli/dist/cli.cjs:757:15
```

```
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: [32mslug: [39m       polygon-create-a-donation-dapp-on-polygon
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: [32mtags: [39m
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:   [32m- [39mPolygon
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:   [32m- [39mJS/TS
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:   [32m- [39mSolidity
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:   [32m- [39mJavascript
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: [32mtitle: [39m      Create a donation dApp on Polygon
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: [32mdifficulty: [39m Beginner
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: [32mdescription: [39mMigrated tutorial from LEARN.V2 
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: [32mcontent: [39m
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:   [32mindex: [39m
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:   [32mcontent/index: [39m
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:     [32mmdx: [39m
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:       [32mname: [39m       index.mdx
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:       [32mpath: [39m       content/index.mdx
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:       [32mdigest: [39m     c1d18c1f486c9af6c40b7671ea6dc5d297f523e889321c2cd87b609c96bc3737
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:       [32marweaveHash: [39mQCI9bM435pJ5veKHrK-uyqtdQEC9RSSm_G2mDi-CpBQ
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: 
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:         🛑 The tutorial is not ready to publish/update. 🚧 state: funded
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish:         
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: error Command failed with exit code 1.
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@builderdao-learn/polygon-create-a-donation-dapp-on-polygon:content:publish: command finished with error, but continuing...
```

### CODE REVIEW

**Comment by silentlight** [comment]
@Necmttn @zurgl is this one `polygon-create-a-donation-dapp-on-polygon` migrated from Figment Learn or proposal created by testers? Do you know? If created by testers than I think that error is expected.

For first error, is there a way to retry just that one tutorial?

**Comment by zurgl** [comment]
@silentlight I do confirm `polygon-create-a-donation-dapp-on-polygon` is migrated from Figment Learn

**Comment by Necmttn** [comment]
> For first error, is there a way to retry just that one tutorial? 
yeah its failed as expected because  in the code logic i do only allow uploading to arweave if the proposal is already `readyToPublish` or `published` since this particular one was `funded` state it failed. 
i will manual set the state to readyToPublish and deploy.

**Comment by Necmttn** [comment]
Uploaded 🙌

**Review by zurgl — APPROVED** [review]
LGTM

**Pull request merged**
