### PR TITLE
Clean up tutorials from testing

### PR DESCRIPTION
**Pull request by pyr0gan**
As per https://figmentio.atlassian.net/browse/LR-362

- Also removed a duplicate tutorial:
  - `tutorials/avalanche-deploy-pangolin-to-local-testnet` was duplicate of `tutorials/avalanche-deploy-pangolin-to-your-local-testnet-and-create-token-pair`

### CODE REVIEW

**Comment by Necmttn** [comment]
@pyr0gan can you add these slugs to @builderdao/data/deprecated.ts as well.

**Review by Necmttn — CHANGES_REQUESTED** [review]
need this test tutorial slugs in deprecated slug list.

**Comment by pyr0gan** [comment]
> need this test tutorial slugs in deprecated slug list.

✅ Got it!

**Review by Necmttn — APPROVED** [review]
LGTM

**Review by silentlight — APPROVED** [review]
LGTM

**Pull request merged**
